### ISSUE TITLE
Why PHP???

### ISSUE THREAD

**Issue by Xd-pro** [DANIHEX/SynapseNet#4]

**Comment by Errorforvirus** [comment]
why not?

**Comment by Xd-pro** [comment]
because php is not rich in libraries for non-web uses and isn't really type safe and is really slow. it would be much better to use Go, NodeJS, Scalar etc.

**Comment by DANIHEX** [comment]
Yeah, You’re right but it’s not an issue bro. Support for those languages are in plan for future not now.

**Comment by Xd-pro** [comment]
if it's written in php it can't support other languages

**Comment by DANIHEX** [comment]
No one said we’re gonna include other languages in this PHP version of SynapseNet.
